services:
  flask:
    image: youtian95/cncityrisk:latest
    restart: always
    networks:
      - app-network
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - PYTHONUNBUFFERED=1
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: youtian95/cncityrisk-nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
