services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: cncityrisk:local
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - PYTHONUNBUFFERED=1

networks:
  app-network:
    driver: bridge
